package cipm.consistency.cpr.pcmjava.logger;

public enum PcmCprEntryKey {
	USER_INTERACTION, USER_INTERACTION_STATE, AFFECTED_PCM_ELEMENTS, AFFECTED_JAVA_ELEMENTS,
	
	CONFLICT_RESOLUTION_STRATEGY,
	
	ASKED_FEATURES, ASKED_CORRESPONDENCE, COMPUTE_IF_ABSENT,
	
	RECEIVED_FEATURES, RECEIVED_CORRESPONDENCES,
	
	REPORTED_FEATURES, REPORTED_CORRESPONDENCES,
}
