package cipm.consistency.cpr.pcmjava.logger;

public enum PcmUserInteractionState {
	//
	REGISTERED,
	//
	TRIGGERED,
	//
	MANUAL_INTERVENTION,
	//
	//
	INTERCEPTED_BY_CONFLICT_RESOLUTION_STRATEGY,
	//
	PARTIALLY_INTERCEPTED_BY_CONFLICT_RESOLUTION_STRATEGY,
	//
	//
	INTERCEPTED_BY_PREVIOUS_USER_INTERACTION_ANSWER,
	//
	PARTIALLY_INTERCEPTED_BY_PREVIOUS_USER_INTERACTION_ANSWER,
	//
	//
	PREVENTED_BY_CHANGE_PREPROCESSING,
	//
	//
	CONFLICT_BETWEEN_CONFLICT_RESOLUTION_STRATEGIES,
	//
	CONFLICT_BETWEEN_PREVIOUS_USER_INTERACTION_ANSWERS,
	//
	//
	UNHANDLED;
}
