<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>si</artifactId>
		<version>0.2.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>cipm.consistency.designtime.instrumentation2</artifactId>
	<dependencies>

		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.osgi</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.e4.ui.model.workbench</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.e4.ui.di</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.e4.ui.services</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.core</groupId>
			<artifactId>org.eclipse.core.resources</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.equinox.registry</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.emftext.language.java</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.sourcecodedecorator</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.correspondence</artifactId>
		</dependency>
		<dependency>
			<groupId>org.palladiosimulator.core</groupId>
			<artifactId>org.palladiosimulator.pcm</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.kdmhelper</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.core</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.text</groupId>
			<artifactId>org.eclipse.text</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.cipm</groupId>
			<artifactId>tools.cipm.models.instrumentation</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.commitintegration</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.models</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.vsum</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>