<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>si</artifactId>
		<version>0.2.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.finegrained</artifactId>
	<dependencies>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.xbase.lib</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.lib</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtend.lib.macro</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.emftext.language.java</artifactId>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.gast2seff</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.sourcecodedecorator</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.kdmhelper</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.core</groupId>
			<artifactId>org.eclipse.core.resources</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.change</artifactId>
		</dependency>
		<dependency>
			<groupId>org.palladiosimulator.core</groupId>
			<artifactId>org.palladiosimulator.pcm</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.correspondence</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.atomic</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.somox.util</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>org.splevo.jamopp.diffing</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements.extended</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.propagation</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>