<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>si</artifactId>
		<version>0.2.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>cipm.consistency.cpr.javapcm.teammates</artifactId>

	<dependencies>

		<dependency>
			<groupId>tools.mdsd</groupId>
			<artifactId>org.emftext.language.java</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.correspondence</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.interaction</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.dsls.reactions.runtime</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtend</groupId>
			<artifactId>org.eclipse.xtend.lib</artifactId>
		</dependency>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtend.lib.macro</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.change.atomic</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements.pojotransformations</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements.extended</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>tools.vitruv.applications.pcmjava.seffstatements.finegrained</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.commitintegration.settings</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.cpr.javapcm.msa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.palladiosimulator.core</groupId>
			<artifactId>org.palladiosimulator.pcm</artifactId>
		</dependency>
		<dependency>
			<groupId>cipm.consistency</groupId>
			<artifactId>cipm.consistency.cpr.util</artifactId>
		</dependency>
		<dependency>
			<groupId>tools.vitruv</groupId>
			<artifactId>tools.vitruv.applications.util.temporary</artifactId>
		</dependency>
	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<release>11</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/java</source>
								<source>src-gen</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>