<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>bundles</artifactId>
		<version>0.2.0-SNAPSHOT</version>
	</parent>
	<artifactId>si</artifactId>
	<packaging>pom</packaging>
	<name>Bundles for second Eclipse instance</name>

	<repositories>
       	  <repository>
             <id>cipm-mvn</id>
             <name>CIPM's Maven Repository</name>
             <url>https://CIPM-tools.github.io/updatesite/mvn</url>
          </repository>
   	</repositories>

	<dependencyManagement>
	 <dependencies>
	  <dependency>
    		 <groupId>org.eclipse.jgit</groupId>
    		 <artifactId>org.eclipse.jgit</artifactId>
    		 <version>6.3.0.202209071007-r</version>
	  </dependency>
          <dependency>
    		<groupId>commons-io</groupId>
    		<artifactId>commons-io</artifactId>
    		<version>2.8.0</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.xtend</groupId>
    		<artifactId>org.eclipse.xtend.lib</artifactId>
    		<version>2.28.0</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.emf</groupId>
    		<artifactId>org.eclipse.emf.edit</artifactId>
    		<version>2.23.0</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.xtext</groupId>
    		<artifactId>org.eclipse.xtext.testing</artifactId>
    		<version>2.43.0.M2</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.core</groupId>
    		<artifactId>org.eclipse.core.resources</artifactId>
    		<version>3.7.100</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.platform</groupId>
    		<artifactId>org.eclipse.equinox.registry</artifactId>
    		<version>3.12.600</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.jdt</groupId>
    		<artifactId>org.eclipse.jdt.core</artifactId>
    		<version>3.45.0</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.text</groupId>
    		<artifactId>org.eclipse.text</artifactId>
    		<version>3.5.101</version>
	  </dependency>
	  <dependency>
    		<groupId>org.apache.commons</groupId>
    		<artifactId>commons-lang3</artifactId>
    		<version>3.20.0</version>
	  </dependency>
	  <dependency>
    		<groupId>org.eclipse.xtext</groupId>
    		<artifactId>org.eclipse.xtext</artifactId>
    		<version>2.43.0.M2</version>
	  </dependency>


	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.settings</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.base.shared</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.tools.evaluation.data</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.models</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.vsum</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>org.splevo.diffing</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.diff.util</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.javapcm</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.pojotransformations</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.extended</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.finegrained</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.util</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.javapcm.msa</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.lang.lua</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.lang.lua.runtimedata</artifactId>
            	<version>${project.version}</version>
          </dependency>


	 </dependencies>
	</dependencyManagement>

	<modules>
		<module>cipm.consistency.commitintegration</module>
		<module>cipm.consistency.commitintegration.lang.lua</module>
		<module>cipm.consistency.commitintegration.lang.lua.runtimedata</module>
		<module>cipm.consistency.cpr.javaim</module>
		<module>cipm.consistency.cpr.javapcm.additional.validation</module>
		<module>cipm.consistency.cpr.javapcm.msa</module>
		<module>cipm.consistency.cpr.javapcm.teammates</module>
		<module>cipm.consistency.cpr.pcmim</module>
		<module>cipm.consistency.designtime.instrumentation2</module>
		<module>cipm.consistency.models</module>
		<module>cipm.consistency.tools.evaluation.data</module>
		<module>cipm.consistency.vsum</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.extended</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.finegrained</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.pojotransformations</module>
		<module>cipm.consistency.cpr.util</module>
		<module>../fi/cipm.consistency.commitintegration.settings</module>
		<module>../fi/cipm.consistency.base.shared</module>
		<module>../fi/org.splevo.diffing</module>
		<module>../fi/cipm.consistency.commitintegration.diff.util</module>
	</modules>

</project>