<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>cipm.consistency</groupId>
		<artifactId>bundles</artifactId>
		<version>0.2.0-SNAPSHOT</version>
	</parent>
	<artifactId>si</artifactId>
	<packaging>pom</packaging>
	<name>Bundles for second Eclipse instance</name>

	<repositories>
       	  <repository>
             <id>cipm-mvn</id>
             <name>CIPM's Maven Repository</name>
             <url>https://CIPM-tools.github.io/updatesite/mvn</url>
          </repository>
   	</repositories>

	<dependencyManagement>
	 <dependencies>


	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.settings</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.base.shared</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.tools.evaluation.data</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.models</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.vsum</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>org.splevo.diffing</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>org.splevo.jamopp.diffing</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>org.splevo.jamopp.extraction</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>org.splevo.commons</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.diff.util</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.javapcm</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.pojotransformations</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.extended</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>tools.vitruv.applications.pcmjava.seffstatements.finegrained</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.util</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.cpr.javapcm.msa</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.lang.lua</artifactId>
            	<version>${project.version}</version>
          </dependency>
	  <dependency>
            	<groupId>cipm.consistency</groupId>
            	<artifactId>cipm.consistency.commitintegration.lang.lua.runtimedata</artifactId>
            	<version>${project.version}</version>
          </dependency>


	 </dependencies>
	</dependencyManagement>

	<modules>
		<module>cipm.consistency.commitintegration</module>
		<module>cipm.consistency.commitintegration.lang.lua</module>
		<module>cipm.consistency.commitintegration.lang.lua.runtimedata</module>
		<module>cipm.consistency.cpr.javaim</module>
		<module>cipm.consistency.cpr.javapcm.additional.validation</module>
		<module>cipm.consistency.cpr.javapcm.msa</module>
		<module>cipm.consistency.cpr.javapcm.teammates</module>
		<module>cipm.consistency.cpr.pcmim</module>
		<module>cipm.consistency.designtime.instrumentation2</module>
		<module>cipm.consistency.models</module>
		<module>cipm.consistency.tools.evaluation.data</module>
		<module>cipm.consistency.vsum</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.extended</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.finegrained</module>
		<module>tools.vitruv.applications.pcmjava.seffstatements.pojotransformations</module>
		<module>cipm.consistency.cpr.util</module>
		<module>../fi/cipm.consistency.commitintegration.settings</module>
		<module>../fi/cipm.consistency.base.shared</module>
		<module>../fi/org.splevo.commons</module>
		<module>../fi/org.splevo.diffing</module>
		<module>../fi/org.splevo.jamopp.diffing</module>
		<module>../fi/org.splevo.jamopp.extraction</module>
		<module>../fi/cipm.consistency.commitintegration.diff.util</module>
	</modules>

</project>